name: facereq_mobile
description: "Face Recognition Attendance App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ===== NETWORK & STORAGE =====
  http: ^1.1.0
  shared_preferences: ^2.2.2

  # ===== LOCATION =====
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0
  permission_handler: ^11.4.0
  location: ^8.0.1

  # ===== CAMERA & IMAGE =====
  camera: ^0.10.0
  path_provider: ^2.0.15
  image: ^4.0.17

  # ===== AUTH =====
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # ===== UI ASSETS =====
    - assets/images/logo.png
    - assets/images/profile.png
    - assets/images/logosmk.png


    # ===== ANDROID ML ASSETS (WAJIB) =====
    - android/app/src/main/assets/face_landmarker.task
    - android/app/src/main/assets/mobilefacenet.tflite
